export const sheetList = {
    id: "yZtRK1",
    sheetOrder: ["7SAQbCZanfZy5x3gSoZyQ"],
    name: "",
    appVersion: "0.2.5",
    locale: "zhCN",
    styles: {
        YquVXa: { bg: { rgb: "#CD0F0F" }, cl: null },
        "Ul-Tg7": { bg: { rgb: "#CD0F0F" }, cl: { rgb: "#FFFFFF" } },
    },
    sheets: {
        "7SAQbCZanfZy5x3gSoZyQ": {
            id: "7SAQbCZanfZy5x3gSoZyQ",
            name: "测试报表填报",
            tabColor: "",
            hidden: 0,
            rowCount: 1000,
            columnCount: 20,
            zoomRatio: 1,
            freeze: { xSplit: 0, ySplit: 0, startRow: -1, startColumn: -1 },
            scrollTop: 0,
            scrollLeft: 0,
            defaultColumnWidth: 88,
            defaultRowHeight: 24,
            mergeData: [],
            cellData: {
                "0": {
                    "0": { v: "项目", t: 1, s: "Ul-Tg7" },
                    "1": { v: "容器", t: 1, s: "Ul-Tg7" },
                    "2": { v: "事件", t: 1, s: "Ul-Tg7" },
                    "3": { v: "时间", t: 1, s: "Ul-Tg7" },
                    "4": { v: "级别", t: 1, s: "Ul-Tg7" },
                    "5": { s: "Ul-Tg7" },
                },
                "1": {
                    "0": {
                        v: "项目",
                        t: 4,
                        custom: { key: "XM" },
                        s: "Ul-Tg7",
                    },
                    "1": {
                        v: "容器",
                        t: 1,
                        custom: { key: "RQ" },
                        s: "Ul-Tg7",
                    },
                    "2": {
                        v: "事件",
                        t: 1,
                        custom: { key: "SJ" },
                        s: "Ul-Tg7",
                    },
                    "3": {
                        v: "时间",
                        t: 1,
                        custom: { key: "Time" },
                        s: "Ul-Tg7",
                    },
                    "4": {
                        v: "级别",
                        t: 1,
                        custom: { key: "JB" },
                        s: "Ul-Tg7",
                    },
                    "5": { s: "Ul-Tg7" },
                },
                "2": {
                    "0": {
                        v: "项目",
                        t: 4,
                        custom: { key: "XM" },
                        s: "Ul-Tg7",
                    },
                    "1": {
                        v: "容器",
                        t: 1,
                        custom: { key: "RQ" },
                        s: "Ul-Tg7",
                    },
                    "2": {
                        v: "事件",
                        t: 1,
                        custom: { key: "SJ" },
                        s: "Ul-Tg7",
                    },
                    "3": {
                        v: "时间",
                        t: 1,
                        custom: { key: "Time" },
                        s: "Ul-Tg7",
                    },
                    "4": {
                        v: "级别",
                        t: 1,
                        custom: { key: "JB" },
                        s: "Ul-Tg7",
                    },
                    "5": { s: "Ul-Tg7" },
                },
                "3": {
                    "0": {
                        v: "项目",
                        t: 4,
                        custom: { key: "XM" },
                        s: "Ul-Tg7",
                    },
                    "1": {
                        v: "容器",
                        t: 1,
                        custom: { key: "RQ" },
                        s: "Ul-Tg7",
                    },
                    "2": {
                        v: "事件",
                        t: 1,
                        custom: { key: "SJ" },
                        s: "Ul-Tg7",
                    },
                    "3": {
                        v: "时间",
                        t: 1,
                        custom: { key: "Time" },
                        s: "Ul-Tg7",
                    },
                    "4": {
                        v: "级别",
                        t: 1,
                        custom: { key: "JB" },
                        s: "Ul-Tg7",
                    },
                    "5": { s: "Ul-Tg7" },
                },
                "4": {
                    "0": {
                        v: "项目",
                        t: 4,
                        custom: { key: "XM" },
                        s: "Ul-Tg7",
                    },
                    "1": {
                        v: "容器",
                        t: 1,
                        custom: { key: "RQ" },
                        s: "Ul-Tg7",
                    },
                    "2": {
                        v: "事件",
                        t: 1,
                        custom: { key: "SJ" },
                        s: "Ul-Tg7",
                    },
                    "3": {
                        v: "时间",
                        t: 1,
                        custom: { key: "Time" },
                        s: "Ul-Tg7",
                    },
                    "4": {
                        v: "级别",
                        t: 1,
                        custom: { key: "JB" },
                        s: "Ul-Tg7",
                    },
                    "5": { s: "Ul-Tg7" },
                },
                "5": {
                    "0": { s: "Ul-Tg7" },
                    "1": { s: "Ul-Tg7" },
                    "2": { s: "Ul-Tg7" },
                    "3": { s: "Ul-Tg7" },
                    "4": { s: "Ul-Tg7" },
                    "5": { s: "Ul-Tg7" },
                },
                "6": {
                    "0": { s: "Ul-Tg7" },
                    "1": { s: "Ul-Tg7" },
                    "2": { s: "Ul-Tg7" },
                    "3": { s: "Ul-Tg7" },
                    "4": { s: "Ul-Tg7" },
                    "5": { s: "Ul-Tg7" },
                },
                "7": {
                    "0": { s: "Ul-Tg7" },
                    "1": { s: "Ul-Tg7" },
                    "2": { s: "Ul-Tg7" },
                    "3": { s: "Ul-Tg7" },
                    "4": { s: "Ul-Tg7" },
                    "5": { s: "Ul-Tg7" },
                },
                "8": {
                    "0": { s: "Ul-Tg7" },
                    "1": { s: "Ul-Tg7" },
                    "2": { s: "Ul-Tg7" },
                    "3": { s: "Ul-Tg7" },
                    "4": { s: "Ul-Tg7" },
                    "5": { s: "Ul-Tg7" },
                },
                "9": {
                    "0": { s: "Ul-Tg7" },
                    "1": { s: "Ul-Tg7" },
                    "2": { s: "Ul-Tg7" },
                    "3": { s: "Ul-Tg7" },
                    "4": { s: "Ul-Tg7" },
                    "5": { s: "Ul-Tg7" },
                },
            },
            rowData: {
                "0": { hd: 0, h: 24, ah: 24 },
                "1": { hd: 0, h: 24, ah: 24 },
                "2": { hd: 0, h: 24, ah: 24 },
            },
            columnData: {},
            showGridlines: 1,
            rowHeader: { width: 46, hidden: 0 },
            columnHeader: { height: 20, hidden: 0 },
            selections: ["A1"],
            rightToLeft: 0,
        },
    },
    resources: [],
};

export const draggableList = [
    {
        label: "项目",
        value: "XM",
    },
    {
        label: "容器",
        value: "RQ",
    },
    {
        label: "事件",
        value: "SJ",
    },
    {
        label: "时间",
        value: "Time",
    },
    {
        label: "级别",
        value: "JB",
    },
];
